language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t jakub19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jakub19/react-test npm test -- --coverage

after_success:
  - docker build -t jakub19/multi-client ./client
  - docker build -t jakub19/multi-nginx ./nginx
  - docker build -t jakub19/multi-server ./server
  - docker build -t jakub19/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jakub19/multi-client
  - docker push jakub19/multi-nginx
  - docker push jakub19/multi-server
  - docker push jakub19/multi-worker